version: '3'
services:
  # dev:
  #   image: node:12
  #   volumes:
  #     - nodemodules:/usr/src/service/node_modules
  #     - .:/usr/src/service
  #   environment:
  #     - NODE_ENV=development
  #   working_dir: /usr/src/service
  #   command: npm run dev
  #   ports:
  #     - "3000:3000"
  server:
    entrypoint: ./docker-scripts/entrypoint.sh
    build: .
    volumes:
      - ./usr/src/service
    depends_on:
      - prisma
      # - dev
    ports:
      - "4000:4000"
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            user: root
            password: prisma
            rawAccess: true
            port: 3306
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql 

volumes:
  nodemodules:
    external: true
  mysql: