version: '2'

services:

  base:
    image: node:12
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service/
    working_dir: /usr/src/service/
    environment:
      - DEBUG=1

  install:
    extends:
      service: base
    command: npm install -g graphql-cli prisma nodemon 
    command: npm i

  build:
    extends:
      service: base
    command: npm run build

  create-bundles:
    extends:
      service: base
    command: npm run create-bundles

volumes:
  nodemodules:
    external: true
  mysql: